on:
  push:
    branches:
      - main
name: ğŸ‘» Deploy server
jobs:
  web-deploy:
    name: ğŸ‘¾ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¤– Codigo mais recente
        uses: actions/checkout@v2

      - name: ğŸ“ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          exclude: "[**/.git*, **/.git*/**, **/.github*, **/.github*/**, **/.vscode*, **/.vscode*/**, .eslintignore, .eslintrc.js, .prettierrc, .prettierignore, README.md]"
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}